### ISSUE TITLE
Forget subtract 15 from added exponent

### ISSUE THREAD

**Issue by EduardoWang** [suoglu/Fixed-Floating-Point-Adder-Multiplier#3]
in file Fixed-Floating-Point-Adder-Multiplier/Sources/adder-multiplier.v line 127
you add 2 exponents together but forget to subtract 15 to it, leading to an incorrect result.

**Comment by suoglu** [comment]
Thank you for pointing out. I am aware of the issue. I was planing to apply bias at one of the calculation statements, after line 133. Probably I will fix it with other issues of that module. Leaving this issue open until it is fixed.

**Comment by suoglu** [comment]
Fixed on 8c26ecc890aaf7a14210d185dea097adeabc1ba2
